### ISSUE TITLE
The checkout page does not show the product quantity in the product quantity input box.

### ISSUE THREAD

**Issue by chrislais** [saleor/react-storefront#811] opened 2023-04-06 13:32 UTC
### Summary

The checkout page does not show the product quantity in the product quantity input box.
![WX20230406-212510@2x](https://user-images.githubusercontent.com/65403988/230391977-c069f366-49dd-4da5-9035-1b909e4f884d.png)

### Steps to reproduce

1. Open [demo site](https://demo.saleor.io/) 
2. Add product to cart
3. Click the shopping bag to checkout
4. Click the quantity input box

**Comment by mmiszy** [comment] 2023-04-30 22:47
I cannot reproduce it. Closing due to lack of environment details or a minimal reproducible example.

**Closed by mmiszy** 2023-04-30 22:47 UTC
