### ISSUE TITLE
app-checkout Dashboard opens error

### ISSUE THREAD

**Issue by dxrvip** [saleor/react-storefront#611] opened 2022-11-10 02:23 UTC
### Summary

I follow the configuration document of saleor-app-checkout, but when I open the app in the background panel, the configuration page reports an error

### Steps to reproduce

` 1 of 3 unhandled errors

Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

`
`Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error`
`Unhandled Runtime Error
Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.`

![image](https://user-images.githubusercontent.com/54361416/200984771-08a2fa34-032a-4c56-b2de-1068ed1d0782.png)
![image](https://user-images.githubusercontent.com/54361416/200984840-2b1fc478-b4d2-4a40-ad94-a05997930422.png)
![image](https://user-images.githubusercontent.com/54361416/200984868-d45cfa05-9153-44d0-bbc5-5a99e7e2e792.png)

## System:
 - OS: macOS 12.6
 - CPU: (8) arm64 Apple M1
 - Memory: 88.53 MB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 18.11.0 - /opt/homebrew/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 8.19.2 - /opt/homebrew/bin/npm
## Browsers:
 - Chrome: 106.0.5249.119
 - Safari: 16.0

pnpm version = 7.14.0

**Comment by kendrice** [comment] 2022-11-11 08:02
Are you in China? Me too. study together

**Comment by mmiszy** [comment] 2022-11-21 12:22
Duplicate of #589

**Closed by mmiszy** 2022-11-21 12:22 UTC
