### ISSUE TITLE
Add "pay for order" ability to order confirmation

### ISSUE THREAD

**Issue by bmigirl** [saleor/react-storefront#394] opened 2022-08-17 11:50 UTC
Currently we have an endpoint to pay for the order, but it still required payment method and payment provider to be passed from checkout. Wee need to figure out what would be the best way to do that

**Comment by mmiszy** [comment] 2022-11-02 19:36
Duplicate of https://github.com/saleor/react-storefront/issues/311

**Closed by mmiszy** 2022-11-02 19:36 UTC
Labels: checkout-storefront
